# Generated by Django 3.2.9 on 2021-11-13 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('status', models.CharField(max_length=100)),
                ('scheduledDate', models.DateTimeField(blank=True, null=True)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('assessment', models.TextField()),
                ('plan', models.TextField()),
                ('remark', models.TextField()),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('appointmentID', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('remark', models.TextField()),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('DoctorNoteID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.doctornote')),
            ],
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='test/')),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('test', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.test')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription', models.TextField()),
                ('remark', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='Pharmacy/')),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('DoctorNoteID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.doctornote')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('remark', models.TextField()),
                ('creator', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('prescription', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.prescription')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.status')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hopitalNo', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('othername', models.CharField(max_length=100)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('emailAd', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('matric_staff', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('medicalCondition', models.TextField()),
                ('allergies', models.TextField()),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloodGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.bloodgroup')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.gender')),
                ('genotype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.genotype')),
                ('maritalStatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.maritalstatus')),
                ('patientType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.patienttype')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('remark', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='Labtest/')),
                ('creator', models.CharField(max_length=100)),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.status')),
                ('test', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.labtestrequest')),
            ],
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='TestType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.testtype'),
        ),
        migrations.AddField(
            model_name='doctornote',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.status'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='AppointmentTypeID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.appointmenttype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.patient'),
        ),
    ]
