# Generated by Django 3.2.9 on 2021-11-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHospital', '0002_appointment_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
