# Generated by Django 3.2.9 on 2021-11-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CHospital', '0003_alter_appointment_createdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hopitalNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
