# Generated by Django 3.2.9 on 2021-11-23 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CHospital', '0005_auto_20211123_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodgroup',
            name='createDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bloodgroup',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='createDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
