# Generated by Django 3.2.9 on 2021-11-23 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CHospital', '0007_auto_20211123_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
