# Generated by Django 3.2.9 on 2021-11-24 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CHospital', '0012_alter_appointment_patientid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.patient'),
        ),
    ]
