# Generated by Django 3.2.9 on 2022-01-08 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211113_1229'),
        ('CHospital', '0014_auto_20220108_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseDrugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('remark', models.TextField()),
                ('createDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('drugs', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.drugs')),
                ('patientID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CHospital.patient')),
            ],
        ),
    ]
