# Generated by Django 3.2.9 on 2022-01-12 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CHospital', '0018_auto_20220108_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugsrecord',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
